[buildPlans.iosevka-evilroot]            # <iosevka-evilroot> is your plan name
family = "Iosevka evilroot"              # Font menu family name
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-evilroot.variants]
inherits = "ss09"

[buildPlans.iosevka-evilroot.metric-override]
leading = 1250

[buildPlans.iosevka-evilroot.compatibility-ligatures]
enables = ["center-ops", "arrow"]

[buildPlans.iosevka-evilroot.variants.design]
f = 'tailed'
g = 'doublestorey'
m = 'shortleg'
y = 'curly'
underscore = 'low'
percent = 'dots'
number-sign = 'slanted'
at = 'threefold'
dollar = 'open'

# All weights would built and mapped to default shape/CSS
[buildPlans.iosevka-evilroot.weights.regular]
shape = 400                            # Weight for glyph shapes
menu  = 400                            # Weight for menu name
css   = 400                            # Weight for WebFont CSS

[buildPlans.iosevka-evilroot.weights.bold]
shape = 700
menu  = 700
css   = 700

# Override default building slant sets
# When this section is absent, all slants would be built.
[buildPlans.iosevka-evilroot.slopes]
upright = "normal"
italic = "italic"
oblique = "oblique"
